name: starchain_v2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.5+2014

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  cached_network_image: ^3.0.0
  octo_image: ^1.0.0
  camera: ^0.8.1
  photo_view: ^0.11.1
  connectivity: ^3.0.3
  dartz: ^0.10.0-nullsafety.1
  internet_connection_checker: ^0.0.1
  equatable: ^2.0.0
  rxdart: ^0.26.0
  path_provider: ^2.0.1
  flutter_bloc: ^7.0.0
  hydrated_bloc: ^7.0.0
  auto_route: ^2.2.0
  json_annotation: ^4.0.0
  freezed_annotation: ^0.14.2
  get_it: ^7.0.0
  google_maps_flutter: ^2.0.2
  dio: ^4.0.0
  hexcolor: ^2.0.3
  kt_dart: ^0.9.0
  injectable: ^1.4.1
  shared_preferences: ^2.0.5
  flutter_typeahead: ^3.1.1
  barcode: ^2.1.0
  barcode_widget: ^2.0.1
  snapping_sheet: ^3.0.0+2
  fluttercontactpicker: ^4.4.0
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  firebase_messaging: ^10.0.4
  cloud_firestore: ^2.4.0
  flutter_screenutil: ^5.0.0+2
  im_stepper: ^0.1.3
  plugin_platform_interface: ^2.0.0
  pin_code_fields: ^7.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  image_picker: ^0.7.3
  another_flushbar: ^1.10.17
  flutter_barcode_scanner: ^2.0.0
  mask_text_input_formatter: ^2.0.0
  share: ^2.0.1
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.0.3
  ntp: ^2.0.0
  flutter:
    sdk: flutter
  sms_retriever:
    path: ../flutter_packages/sms_retriever
  dio_http_cache:
    path: ../flutter_packages/dio_http_cache
  flutter_staggered_grid_view: ^0.4.0
  auto_size_text: ^3.0.0-nullsafety.0
  great_list_view: ^0.0.10+1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  pdf: ^3.4.2
  printing: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.14.2
  auto_route_generator: ^2.1.0
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
